### ISSUE TITLE
Testing for different input Videos

### ISSUE THREAD

**Issue by suraj-ajjampur** [cu-ecen-aeld/final-project-aasu8675#2]
Replacing the video in the input directory with other videos and test them out

Dod
- [x] Source videos into the jetson nano board
- [x] Stress test application for varying input video lengths, frames per second etc
- [x]  Check for output time to process

Blockers:
Sourcing videos which will provide meaningful output that can be tested against the application source code.
Transferring videos onto jetson nano which will need headless operation of the Jetson nano to transfer videos or an alternate mechanism.

**Comment by aasu8675** [comment]
Tested the same configuration with a different input.

- I was unable to ssh into the jetson nano to use the headless version. Due to time limitation I tried another video which was built as part of the tegra image called pedestrians.mp4 which was used for analysis.
- With the current configuration the setup could process a maximum of 10 frames per second.
- The output time to process the video was quite long, considering the length of the video. Next sprints will require us to analyze data for real time input.


- A few changes were done to use the new video. The video was copied into the data-default directory. The init script was updated to copy the local file into the dockerized container which will be used for processing.
Screenshots of testing are shown below:
![image](https://github.com/cu-ecen-aeld/final-project-aasu8675/assets/123521880/afce0de9-a503-4856-afee-7938064d3fef)

Initially person 5 crosses the line which has increased the pedestrian count by 1. 

The configuration used extends the line till the ending of the frame. In the image below, person 16 crosses that line which increases the pedestrian count.

![image](https://github.com/cu-ecen-aeld/final-project-aasu8675/assets/123521880/42ca9d1b-29b0-474e-aba4-f3561a355047)
